---
# tasks file for azure_dev_wintools
- name: Hyper-V installed
  win_feature:
    name: "Hyper-V"
    include_management_tools: yes
    state: present

- name: Visual Studio Code installed
  win_chocolatey:
    name: vscode
    state: present
    version: "1.42.1"
