---
# tasks file for azure_dev_wintools
- name: Hyper-V installed
  win_feature:
    name: "Hyper-V"
    include_management_tools: yes
    state: present

- name: Visual Studio Code installed
  win_chocolatey:
    name: vscode
    state: present
    version: "1.42.1"

- name: Git installed
  win_chocolatey:
    name: git
    state: present
    version: "2.25.0"

- name: Docker Desktop installed
  win_chocolatey:
    name: docker-desktop
    state: present
    version: "2.2.0.3"
