---
# tasks file for azure_poc_infra_core
- name: Resource group provisioned
  azure_rm_resourcegroup:
    name: "{{resource_group}}"
    location: "{{location}}"
    tags:
      environment: "{{tag_env}}"
  register: azure_rg_poc

- name: Virtual network provisioned
  azure_rm_virtualnetwork:
    resource_group: "{{resource_group}}"
    name: "{{vnet_name}}"
    tags:
      environment: "{{tag_env}}"
    address_prefixes_cidr:
      - "{{vnet_cidr}}"

- name: Subnet db tier provisioned
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    virtual_network: "{{vnet_name}}"
    name: "{{vnet_name}}-subnet-db"
    address_prefix: "{{vnet_cidr_db}}"

- name: Subnet app tier provisioned
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    virtual_network: "{{vnet_name}}"
    name: "{{vnet_name}}-subnet-app"
    address_prefix: "{{vnet_cidr_app}}"

- name: Subnet web tier provisioned
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    virtual_network: "{{vnet_name}}"
    name: "{{vnet_name}}-subnet-web"
    address_prefix: "{{vnet_cidr_web}}"

- name: Subnet dmz tier provisioned
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    virtual_network: "{{vnet_name}}"
    name: "{{vnet_name}}-subnet-dmz"
    address_prefix: "{{vnet_cidr_dmz}}"
