---
- name: POC Deployment
  hosts: localhost
  connection: local
  vars:
    resource_group: "poc_rg"
    location: "southeastasia"
  roles:
    - role: azure_poc_infra_core
      when: poc_state | default('present') == 'present'
  tasks:
    - name: Clean resource group
      azure_rm_resourcegroup:
        name: "{{resource_group}}"
        location: "{{location}}"
        state: "absent"
        force_delete_nonempty: yes
      when: poc_state | default('present') == 'absent'
