---
# tasks file for azure_dev_win19v2
- name: Resource group provisioned
  azure_rm_resourcegroup:
    name: "{{resource_group}}"
    tags:
      environment: "{{tag_env}}"
    location: "{{location}}"
  register: azure_rg_dev

- name: Virtual network provisioned
  azure_rm_virtualnetwork:
    resource_group: "{{resource_group}}"
    name: "{{vnet_name}}"
    address_prefixes_cidr:
      - "10.0.0.0/24"
    tags:
      environment: "{{tag_env}}"

- name: Subnet 01 provisioned
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    virtual_network: "{{vnet_name}}"
    name: "{{vnet_name}}-subnet1"
    address_prefix: "10.0.0.0/28"

- name: Public IP Address provisioned
  azure_rm_publicipaddress:
    resource_group: "{{resource_group}}"
    name: "{{vm_name}}-pip"
    allocation_method: Dynamic
    domain_name_label: "{{vm_name}}-pip-dnsnl"

- name: Network security group provisioned
  azure_rm_securitygroup:
    resource_group: "{{resource_group}}" # required. Name of the resource group the security group belongs to.
    rules:
      - name: allow_rdp
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1001
        direction: Inbound
      - name: allow_powershell_remoting
        protocol: Tcp
        destination_port_range:
          - 5985
          - 5986
        access: Allow
        priority: 1002
        direction: Inbound
    name: "{{vm_name}}-sg"

- name: Network interface provisioned
  azure_rm_networkinterface:
    resource_group: "{{resource_group}}" # required. Name of a resource group where the network interface exists or will be created.
    name: "{{vm_name}}-nic" # required. Name of the network interface.
    subnet_name: "{{vnet_name}}-subnet1" # required. Name of an existing subnet within the specified virtual network. Required when creating a network interface,Use the C(virtual_network)'s resource group.
    virtual_network: "{{vnet_name}}" # required. An existing virtual network with which the network interface will be associated. Required when creating a network interface.,It can be the virtual network's name.,Make sure your virtual network is in the same resource group as NIC when you give only the name.,It can be the virtual network's resource id.,It can be a dict which contains C(name) and C(resource_group) of the virtual network.
    enable_accelerated_networking: true # not required. Specifies whether the network interface should be created with the accelerated networking feature or not
    ip_configurations:
      - name: default
        public_ip_address_name: "{{vm_name}}-pip"
        primary: true
    security_group: "{{vm_name}}-sg"

- name: Development VM provisioned
  azure_rm_virtualmachine:
    resource_group: "{{resource_group}}" # required. Name of the resource group containing the virtual machine.
    name: "{{vm_name}}" # required. Name of the virtual machine.
    managed_disk_type: Standard_LRS # not required. choices: Standard_LRS;Premium_LRS. Managed OS disk type
    network_interface_names: "{{vm_name}}-nic" # not required. List of existing network interface names to add to the VM.,Item can be a str of name or resource id of the network interface.,Item can also be a dict contains C(resource_group) and C(name) of the network interface.,If a network interface name is not provided when the VM is created, a default network interface will be created.,In order for the module to create a new network interface, at least one Virtual Network with one Subnet must exist.
    admin_password: "{{vm_password}}" # not required. Password for the admin username. Not required if the os_type is Linux and SSH password authentication is disabled by setting ssh_password_enabled to false.
    tags:
      environment: "{{tag_env}}"
    vm_size: "{{vm_size}}" # not required. A valid Azure VM size value. For example, 'Standard_D4'. The list of choices varies depending on the subscription and location. Check your subscription for available choices. Required when creating a VM.
    os_disk_size_gb: 200 # not required. Type of OS disk size in GB.
    admin_username: "{{vm_user}}" # not required. Admin username used to access the host after it is created. Required when creating a VM.
    os_type: Windows # not required. choices: Windows;Linux. Base type of operating system.
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: "{{vm_sku}}"
      version: latest

- name: HTTPS WinRM Listener configured
  azure_rm_virtualmachineextension:
    resource_group: "{{resource_group}}" # required. Name of a resource group where the vm extension exists or will be created.
    name: winrm-extension # required. Name of the vm extension
    type_handler_version: "1.9" # not required. The type version of the extension handler.
    auto_upgrade_minor_version: true # not required. Whether the extension handler should be automatically upgraded across minor versions.
    virtual_machine_extension_type: CustomScriptExtension # not required. The type of the extension handler.
    virtual_machine_name: "{{vm_name}}" # not required. The name of the virtual machine where the extension should be create or updated.
    publisher: "Microsoft.Compute" # not required. The name of the extension handler publisher.
    settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'

- name: Public IP Addresses retrieved
  azure_rm_publicipaddress_info:
    name: "{{vm_name}}-pip" # not required. Only show results for a specific Public IP.
    resource_group: "{{resource_group}}" # not required. Limit results by resource group. Required when using name parameter.
  register: demo_vmdev_piplist

- name: Public IP Addresses displayed
  debug:
    msg: "publicipaddresses: {{demo_vmdev_piplist}}"

- name: First public IP address retrieved
  set_fact: demo_vmdev_pip="{{demo_vmdev_piplist | json_query('publicipaddresses[0].ip_address')}}"

- name: "Display PIP: {{demo_vmdev_pip}}"
  debug:
    msg: "PIP: {{demo_vmdev_pip}}"

- name: "WinRM Port online: {{demo_vmdev_pip}}"
  wait_for:
    port: 5986
    host: "{{demo_vmdev_pip}}"
    timeout: 600
